apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mockexchange-posts-api.fullname" . }}
  labels:
    {{- include "mockexchange-posts-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mockexchange-posts-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/database: {{ include (print $.Template.BasePath "/database-secret.yaml") . | sha256sum }}
        {{- if .Values.oauth.enabled }}
        checksum/oauth: {{ include (print $.Template.BasePath "/oauth-secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "mockexchange-posts-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mockexchange-posts-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- if .Values.liveness.initialDelaySeconds }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            {{- end }}
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            {{- if .Values.readiness.initialDelaySeconds }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            {{- end }}
            httpGet:
              path: /actuator/health/readiness
              port: http
          envFrom:
            - secretRef:
                name: {{ include "mockexchange-posts-api.fullname" . }}-database
            {{- if .Values.oauth.enabled }}
            - secretRef:
                name: {{ include "mockexchange-posts-api.fullname" . }}-oauth
            {{- end }}
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: SERVER_SHUTDOWN
              value: graceful
            - name: SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE
              value: 35s
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
