apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockexchange-posts-api.fullname" . }}-oauth
  labels:
    {{- include "mockexchange-posts-api.labels" $ | nindent 4 }}
data:
  {{- with .Values.oauth }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTID: {{ .clientId | b64enc | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTSECRET: {{ .clientSecret | b64enc | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_REDIRECTURI: {{ .redirectUri | b64enc | quote }}
  {{- end }}
