image:
  repository: mockexchange-posts-api

ingress:
  enabled: true
  path: /
  pathType: Prefix
  tls:
    enabled: true

database:
  enabled: true
  secret:
    create: false

oauth:
  enabled: true
  name: github
  secret:
    create: true
