{{ with .Values.s3 }}
{{ if and .enabled (and .accessKeyId .secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockexchange.fullname" $ }}-s3
  labels:
    {{- include "mockexchange.labels" $ | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .secretAccessKey | b64enc | quote }}
{{ end }}
{{ end }}
