apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockexchange-common.fullname" . }}-database
  labels:
    {{- include "mockexchange-common.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{- with .Values.database }}
  SPRING_DATASOURCE_URL: {{ .url | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .username | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .password | b64enc | quote }}
  {{- if .schema }}
  SPRING_DATASOURCE_HIKARI_SCHEMA: {{ .schema | b64enc | quote }}
  {{- end }}
  {{- end }}
