{{ with .Values.s3 }}
{{ if and .enabled (and .accessKeyId .secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockexchange-common.fullname" $ }}-s3
  labels:
    {{- include "mockexchange-common.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  AWS_ACCESS_KEY_ID: {{ .accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .secretAccessKey | b64enc | quote }}
{{ end }}
{{ end }}
