{{- define "mockexchange-common.database-secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockexchange-common.datbaseSecretName" . }}
  labels:
    {{- include "mockexchange-common.labels" $ | nindent 4 }}
data:
  {{- with .Values.database }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:%s" .url | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .username | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .password | b64enc | quote }}
  SPRING_R2DBC_URL: {{ printf "r2dbc:%s" .url | b64enc | quote }}
  SPRING_R2DBC_USERNAME: {{ .username | b64enc | quote }}
  SPRING_R2DBC_PASSWORD: {{ .password | b64enc | quote }}
  {{- if .schema }}
  SPRING_DATASOURCE_HIKARI_SCHEMA: {{ .schema | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- define "mockexchange-common.database-secret" -}}
{{- include "mockexchange-common.util.merge" (append . "mockexchange-common.database-secret.tpl") -}}
{{- end -}}
