{{- define "mockexchange-common.oauth-secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockexchange-common.oauthSecretName" . }}
  labels:
    {{- include "mockexchange-common.labels" $ | nindent 4 }}
data:
  {{- with .Values.oauth }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_{{ .name | upper }}_CLIENTID: {{ .clientId | b64enc | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_{{ .name | upper }}_CLIENTSECRET: {{ .clientSecret | b64enc | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_{{ .name | upper }}_REDIRECTURI: {{ .redirectUri | b64enc | quote }}
  {{- end }}
{{- end }}
{{- define "mockexchange-common.oauth-secret" -}}
{{- include "mockexchange-common.util.merge" (append . "mockexchange-common.oauth-secret.tpl") -}}
{{- end -}}
