{{- define "mockexchange-common.redis-secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockexchange-common.redisSecretName" . }}
  labels:
    {{- include "mockexchange-common.labels" $ | nindent 4 }}
data:
  {{- with .Values.redis }}
  SPRING_REDIS_HOST: {{ .url | b64enc | quote }}
  SPRING_REDIS_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- define "mockexchange-common.redis-secret" -}}
{{- include "mockexchange-common.util.merge" (append . "mockexchange-common.redis-secret.tpl") -}}
{{- end -}}
