{{- define "mockexchange-common.serviceaccount.tpl" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mockexchange-common.serviceAccountName" . }}
  labels:
    {{- include "mockexchange-common.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- define "mockexchange-common.serviceaccount" -}}
{{- include "mockexchange-common.util.merge" (append . "mockexchange-common.serviceaccount.tpl") -}}
{{- end -}}
