name: BFF Image
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - '**/mockexchange-bff/**'
jobs:
  api_image:
    name: Build and push image
    uses: ./.github/workflows/api_image.yaml
    with:
      module: mockexchange-bff
      ecr_repository: mockexchange-bff
      tag: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
