name: GitHub Actions Demo
on:
  push:
    branches:
      - actions
jobs:
  push_image:
    uses: ./.github/workflows/deploy_api.yaml
    with:
      module: mockexchange-posts-api
      ecr_repository: mockexchange-posts-api
      tag: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
