name: Deploy Comments API
on:
  push:
    branches:
      - actions
#    paths:
#      - '**/mockexchange-comments-api/**'
jobs:
  push_image:
    uses: ./.github/workflows/deploy_api.yaml
    with:
      module: mockexchange-comments-api
      ecr_repository: mockexchange-comments-api
      tag: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
