name: Unit tests

on:
  push:
    paths:
      - '**.java'
      - '**.kt'
      - '**.gradle'
      - '**.kts'
      - '**/resources/application*'
      - '**/.github/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
      - '**.kt'
      - '**.gradle'
      - '**.kts'
      - '**/resources/application*'
      - '**/.github/**'
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: ./.github/workflows/jdk_gradle.yaml
      - name: Run tests
        run: ./gradlew test
