name: Unit tests

on:
  push:
    paths:
      - '**.java'
      - '**.kt'
      - '**.gradle'
      - '**.kts'
      - '**/resources/application*'
      - '**/.github/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
      - '**.kt'
      - '**.gradle'
      - '**.kts'
      - '**/resources/application*'
      - '**/.github/**'
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
          cache: gradle
      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: test
